### ISSUE TITLE
pkg_resources not found

### ISSUE THREAD

**Issue by wuffwuff** [asdil12/pymultimonaprs#24]
Hi!

in the  pymultimonaprs git-package is the pkg_resources missing - line 6 in setup.py points to this resources - python gives with 

python setup.py install

the output:

Traceback (most recent call last):                                                                                                      
  File "setup.py", line 6, in <module>                                                                                                  
    import pkg_resources                                                                                                                
ImportError: No module named pkg_resources

Also it seems pymultimonaprs is not running caused of this. I allready installed it months ago on other systems with older versions (no remote access at the moment posible) and it worked well,

br and 73,
oe1wuw

**Comment by asdil12** [comment]
Make sure to that you use python2 and have python2-setuptools installed.

**Comment by MartinHerren** [comment]
I had the same issue the other day when installing pymultimonaprs on a new server and installing "python-pkg-resources" solved it.
I upgraded the README.md on my fork to mention this dependency:
https://github.com/MartinHerren/pymultimonaprs

But installing python2-setuptools will also automatically pull in python-pkg-resources so that will work as well of course.

**Comment by wuffwuff** [comment]
Hi!

Strange, see the full installation:

root@computer:~/scr# git clone https://github.com/asdil12/pymultimonaprs.git                                                
Cloning into 'pymultimonaprs'...                                                                                                        
remote: Counting objects: 324, done.                                                                                                    
remote: Compressing objects: 100% (16/16), done.                                                                                        
remote: Total 324 (delta 5), reused 0 (delta 0), pack-reused 308                                                                        
Receiving objects: 100% (324/324), 862.79 KiB | 560 KiB/s, done.                                                                        
Resolving deltas: 100% (158/158), done.                                                                                                 
root@computer:~/scr# cd pymultimonaprs                                                                                      
root@computer:~/scr/pymultimonaprs# sudo python2 setup.py install                                                           
Traceback (most recent call last):                                                                                                      
  File "setup.py", line 6, in <module>                                                                                                  
    import pkg_resources                                                                                                                
ImportError: No module named pkg_resources                                                                                              
root@computer:~/scr/pymultimonaprs#   

Than I reinstalled python2 and the pyh2 setuptools and than pymultiomnaprs.
It seems it worked, but when I want to start the programm manual with option v this appears:

root@computer:~/scr/pymultimonaprs# pymultimonaprs -v                                                                       
Traceback (most recent call last):                                                                                                      
  File "/usr/local/bin/pymultimonaprs", line 23, in <module>                                                                            
    config = json.load(open(args.config))                                                                                               
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load                                                                         
    **kw)                                                                                                                               
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads                                                                        
    return _default_decoder.decode(s)                                                                                                   
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode                                                                        
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                   
  File "/usr/lib/python2.7/json/decoder.py", line 381, in raw_decode                                                                    
    obj, end = self.scan_once(s, idx)                                                                                                   
ValueError: Expecting , delimiter: line 29 column 31 (char 880) 

no idea, on an older system (rasp) it works fine.

**Comment by asdil12** [comment]
you have a syntax error in your config file (`/etc/pymultimonaprs.json`) in line 29.

**Comment by wuffwuff** [comment]
Works now well - THX! :-)
