### ISSUE TITLE
Issue with subprocess when starting on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by m1geo** [asdil12/pymultimonaprs#26]
Hello all.

When trying to start on my desktop PC, following a successful "python setup.py build" and "python setup.py install".

When starting, I get the following:

> george@zobel:~$ sudo pymultimonaprs -v
> [2016-01-05 01:34:36]     INFO: Starting pymultimonaprs
> [2016-01-05 01:34:36]     INFO: connecting... 178.62.6.243:14580
> [2016-01-05 01:34:36]     INFO: connected
> [2016-01-05 01:34:36]     INFO: # aprsc 2.0.18-ge7666c5
> [2016-01-05 01:34:36]     INFO: login M1GEO (PyMultimonAPRS 1.2.0)
> [2016-01-05 01:34:36]     INFO: # logresp M1GEO verified, server T2LONDON
> Traceback (most recent call last):
>   File "/usr/local/bin/pymultimonaprs", line 96, in <module>
>     mm = Multimon(mmcb,config)
>   File "/usr/local/lib/python2.7/dist-packages/pymultimonaprs/multimon.py", line 14, in __init__
>     self._start()
>   File "/usr/local/lib/python2.7/dist-packages/pymultimonaprs/multimon.py", line 48, in _start
>     stdout=subprocess.PIPE, stderr=open('/dev/null')
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> george@zobel:~$

******* THE SOLUTION *******

Inside the multimon.py file, add "shell=True" as an argument to each call to subprocess.Popen.  Seel new _start(self): below

> 	def _start(self):
> 		if self.config['source'] == 'pulse':
> 			proc_mm = subprocess.Popen(
> 				['multimon-ng', '-a', 'AFSK1200', '-A'],
> 				stdout=subprocess.PIPE, stderr=open('/dev/null'),
> 				**shell=True**
> 			)
> 		else:
> 			if self.config['source'] == 'rtl':
> 				proc_src = subprocess.Popen(
> 					['rtl_fm', '-f', str(int(self.config['rtl']['freq'] * 1e6)), '-s', '22050',
> 					'-p%s' % str(self.config['rtl']['ppm']), '-g', str(self.config['rtl']['gain']),
> 					'-E', 'offset' if self.config['rtl'].get('offset_tuning', False) else 'none',
> 					'-d', str(self.config['rtl'].get('device_index', 0)), '-'],
> 					stdout=subprocess.PIPE, stderr=open('/dev/null'),
> 					**shell=True**
> 				)
> 			elif self.config['source'] == 'alsa':
> 				proc_src = subprocess.Popen(
> 					['arecord', '-D', self.config['alsa']['device'],
> 					'-r', '22050', '-f', 'S16_LE', '-t', 'raw', '-c', '1', '-'],
> 					stdout=subprocess.PIPE, stderr=open('/dev/null'),
> 					**shell=True**
> 				)
> 			proc_mm = subprocess.Popen(
> 				['multimon-ng', '-a', 'AFSK1200', '-A', '-t', 'raw', '-'],
> 				stdin=proc_src.stdout,
> 				stdout=subprocess.PIPE, stderr=open('/dev/null'),
> 				**shell=True**
> 			)
> 			self.subprocs['src'] = proc_src
> 		self.subprocs['mm'] = proc_mm
>

Hope that helps?

George
M1GEO.com

**Comment by m1geo** [comment]
Turns out, multimon-ng wasn't built properly. Apologies! :(
